name: Build and Deploy to GitHub Pages

# Запускати workflow при push в main гілку
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Дозволити запуск вручну
  workflow_dispatch:

# Налаштування дозволів для GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Дозвіл тільки одного деплою за раз
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job для збірки
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      env:
        # Для Vite проектів використовуйте змінні VITE_
        VITE_TMDB_API_KEY: ${{ secrets.REACT_APP_TMDB_API_KEY }}
        VITE_API_BASE_URL: 'https://api.themoviedb.org/3'
        VITE_IMAGE_BASE_URL: 'https://image.tmdb.org/t/p'
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ hashFiles('build') != '' && './build' || './dist' }}

  # Job для деплою
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
